app_name: Legal AI Assistant
version: 2.0.0
debug: false
log_level: INFO
api_base_url: http://localhost:8000
base_dir: /workspace/Legal-AI-ssistant/legal_ai_system
data_dir: /workspace/Legal-AI-ssistant/legal_ai_system/storage
documents_dir: /workspace/Legal-AI-ssistant/legal_ai_system/storage/documents
models_dir: /workspace/Legal-AI-ssistant/legal_ai_system/models
logs_dir: /workspace/Legal-AI-ssistant/legal_ai_system/logs
frontend_dist_path: /workspace/Legal-AI-ssistant/legal_ai_system/frontend/dist
llm_provider: xai
llm_model: grok-3-mini
llm_temperature: 0.7
llm_max_tokens: 4096
ollama_host: http://localhost:11434
ollama_timeout: 60
openai_api_key: null
openai_base_url: null
xai_api_key: null
xai_base_url: https://api.x.ai/v1
xai_model: grok-3-mini
fallback_provider: ollama
fallback_model: llama3.2
vector_store_type: hybrid
embedding_model: all-MiniLM-L6-v2
embedding_dim: 384
pq_m: 8
pq_nbits: 8
metadata_memory_cache_size: 10000
faiss_index_path: /workspace/Legal-AI-ssistant/legal_ai_system/storage/vectors/faiss_index.bin
faiss_metadata_path: /workspace/Legal-AI-ssistant/legal_ai_system/storage/vectors/faiss_metadata.json
document_index_path: /workspace/Legal-AI-ssistant/legal_ai_system/storage/vectors/document_index.faiss
entity_index_path: /workspace/Legal-AI-ssistant/legal_ai_system/storage/vectors/entity_index.faiss
lance_db_path: /workspace/Legal-AI-ssistant/legal_ai_system/storage/vectors/lancedb
lance_table_name: documents
sqlite_path: /workspace/Legal-AI-ssistant/legal_ai_system/storage/databases/legal_ai.db
memory_db_path: /workspace/Legal-AI-ssistant/legal_ai_system/storage/databases/memory.db
violations_db_path: /workspace/Legal-AI-ssistant/legal_ai_system/storage/databases/violations.db
neo4j_uri: bolt://localhost:7687
neo4j_user: neo4j
neo4j_password: CaseDBMS
neo4j_database: neo4j
supported_formats:
- .pdf
- .docx
- .txt
- .md
max_file_size_mb: 100
tesseract_path: null
ocr_languages:
- eng
chunk_size: 1000
chunk_overlap: 200
enable_auto_tagging: true
auto_tag_confidence_threshold: 0.7
tag_history_path: /workspace/Legal-AI-ssistant/legal_ai_system/storage/tag_history.json
feedback_learning_enabled: true
min_feedback_samples: 50
enable_file_watching: true
watch_directories:
- /workspace/Legal-AI-ssistant/legal_ai_system/storage/documents/inbox
- /workspace/Legal-AI-ssistant/legal_ai_system/storage/documents/queue
watch_recursive: true
session_timeout_minutes: null
max_sessions: null
max_context_tokens: null
context_priority_decay: 0.9
auto_summarize_enabled: true
auto_summarize_threshold: null
summary_max_length: null
default_jurisdiction: US
jurisdiction_hierarchy:
- Federal
- State
- County
- Municipal
citation_formats:
- bluebook
- alwd
- mla
- apa
violation_confidence_threshold: null
enable_cross_case_analysis: true
gui_theme: light
window_width: 1400
window_height: 900
gui_update_interval_ms: 100
max_gui_log_lines: 1000
max_concurrent_documents: null
batch_size: null
enable_embedding_cache: true
cache_ttl_hours: null
max_cache_size_mb: null
rate_limit_per_minute: null
enable_request_logging: true
  enable_data_encryption: false
  encryption_key_path: null
  test_data_dir: /workspace/Legal-AI-ssistant/legal_ai_system/tests/data
  enable_test_mode: false
  enable_agent_debugging: false
  save_intermediate_results: false
  enable_spacy_ner: false
  spacy_ner_model: en_core_web_sm
  enable_legal_bert: false
  legal_bert_model_name: nlpaueb/legal-bert-base-uncased
  agents:
    legal_reasoning_engine_config: {}
    knowledge_graph_reasoning_agent_config: {}
